"""create fallas_condiciones_comerciales table

Revision ID: 3c8946c034cc
Revises: 75f15ef2ffa9
Create Date: 2026-08-27 09:58:09.868701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8946c034cc'
down_revision: Union[str, None] = '75f15ef2ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fallas_condiciones_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('condicion_comercial_id', sa.Integer(), nullable=True),
    sa.Column('tiene_falla', sa.Boolean(), nullable=False),
    sa.Column('motivo_falla', sa.Text(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condicion_comercial_id'], ['condiciones_comerciales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_fallas_condiciones_comerciales_id'), 'fallas_condiciones_comerciales', ['id'], unique=False)
    op.drop_constraint(op.f('condiciones_comerciales_pedido_id_fkey'), 'condiciones_comerciales', type_='foreignkey')
    op.drop_column('condiciones_comerciales', 'pedido_id')
    op.drop_column('condiciones_comerciales', 'motivo_falla')
    op.drop_column('condiciones_comerciales', 'tiene_falla')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condiciones_comerciales', sa.Column('tiene_falla', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('condiciones_comerciales', sa.Column('motivo_falla', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('condiciones_comerciales', sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('condiciones_comerciales_pedido_id_fkey'), 'condiciones_comerciales', 'pedidos', ['pedido_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_fallas_condiciones_comerciales_id'), table_name='fallas_condiciones_comerciales')
    op.drop_table('fallas_condiciones_comerciales')
    # ### end Alembic commands ###